/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HCK99wj3W5o
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <Card className="w-full max-w-md mx-auto">
      <CardHeader>
        <CardTitle>File Upload Portal</CardTitle>
        <CardDescription>
          Easily upload your files by dragging and dropping them into the designated area.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="flex flex-col items-center justify-center gap-4 p-8 border-2 border-dashed border-primary rounded-md transition-colors duration-300 hover:border-primary-foreground">
          <CloudUploadIcon className="w-12 h-12 text-primary" />
          <p className="text-center text-muted-foreground">
            Drag and drop your files here, or{" "}
            <Button variant="link" className="inline">
              click to browse
            </Button>
          </p>
        </div>
      </CardContent>
      <CardFooter>
        <div className="flex justify-between">
          <Button variant="outline">Cancel</Button>
          <Button type="submit">Upload</Button>
        </div>
      </CardFooter>
    </Card>
  )
}

function CloudUploadIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242" />
      <path d="M12 12v9" />
      <path d="m16 16-4-4-4 4" />
    </svg>
  )
}
